version: "3"

services:

  # wsgi
  backend:
    build: .
    command: python src/manage.py runserver 0:8000
#    command: tail -f /dev/null
    container_name: backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/srv/project
    depends_on:
      - rabbitmq
      - postgres
      - memcached
    ports:
      - "8000:8000"
      - "8001:8001"

  celery:
    build: .
    command: /bin/bash ./commands/start_celery.sh
    container_name: celery
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./:/srv/project

  celerybeat:
    build: .
    command: /bin/bash ./commands/start_celerybeat.sh
    container_name: celerybeat
    restart: always
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./:/srv/project

  rabbitmq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbitmq
    restart: always
    env_file:
      - .env
    ports:
      - "15672:15672"

  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always

  postgres:
    image: postgres:11.3
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.17.4-alpine
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./static_content:/etc/nginx/static_content/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  pgdata: {}
#      - POSTGRES_PORT: 5432
